server:
  port: 8088
spring:
  application:
    name: txwl
  data:
    mongodb:
      uri: mongodb://localhost:27017/face_platform  #mongodb://admin:admin@10.40.51.33:27018/face_platform
#      uri: mongodb://admin:admin@10.40.51.33:27018/face_platform

#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
#    lettuce.pool.max-active: 8
#    lettuce.pool.max-wait: -1
#    lettuce.pool.max-idle: 8
#    lettuce.pool.min-idle: 0

logging:
  config: classpath:log/logback-spring.xml

# yitu接口地址
OpodDecOrEnc:
  url: http://10.40.51.33:9700

# 接口工具地址
fetchTrack:
  # 为空则默认在jar同级目录
  # windows例:G:\Work\Yitu\demo\fetch_track
  # linux  例:/Yitu/demo/fetch_track
  filePath:
